secrets:
  jwt_secret:
    file: ./secrets/jwt-secret.key

services:
  competitiondb:
    image: postgres:16-alpine
    container_name: competition-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: competition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5398:5432"
    volumes:
      - competition_data:/var/lib/postgresql/data
      - ./competition/init-scripts/competition:/docker-entrypoint-initdb.d
    networks:
      - sports-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d competition"]
      interval: 10s
      retries: 5

  competition-service:
    build: ./competition  # Путь к папке с Dockerfile
    container_name: competition-service
    restart: on-failure
    depends_on:
      competitiondb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://competitiondb:5432/competition
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_PATH: /run/secrets/jwt_secret
    ports:
      - "8082:8080"
    networks:
      - sports-network
    secrets:
      - jwt_secret

volumes:
  competition_data:

networks:
  sports-network:
    driver: bridge
