version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: sports_db
    restart: always
    environment:
      POSTGRES_DB: sports_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5399:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5048:80"

volumes:
  db_data:
